apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: umeq-csi-plugin
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: umeq-csi-plugin
  template:
    metadata:
      labels:
        name: umeq-csi-plugin
    spec:
      containers:
      - args:
        - --csi-address=/csi/csi.sock
        - --kubelet-registration-path=/var/lib/kubelet/plugins/umeq-csi.xiaomakai.com/csi.sock
        - --health-port=9809
        image: k8s.gcr.xfs.pub/sig-storage/csi-node-driver-registrar:v2.5.0
        imagePullPolicy: IfNotPresent
        name: csi-driver-registrar
        ports:
        - containerPort: 9809
          name: healthz
          protocol: TCP
        resources: {}
        volumeMounts:
        - mountPath: /csi
          name: plugin-dir
        - mountPath: /registration
          name: registration-dir
      - command:
        - ./plugin
        env:
        - name: CSI_ENDPOINT
          value: /csi/csi.sock
        - name: AGENT_SERVER
          value: http://192.168.3.11:8080
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        image: kcr.xfs.pub/umeq-csi-plugin:1.0.3
        imagePullPolicy: IfNotPresent
        name: umeq-csi
        resources: {}
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /csi/
          name: plugin-dir
        - mountPath: /var/lib/kubelet/pods/
          mountPropagation: Bidirectional
          name: pods
        - mountPath: /dev/
          name: dev
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      volumes:
      - hostPath:
          path: /var/lib/kubelet/plugins_registry/
          type: Directory
        name: registration-dir
      - hostPath:
          path: /var/lib/kubelet/plugins/umeq-csi.xiaomakai.com/
          type: DirectoryOrCreate
        name: plugin-dir
      - hostPath:
          path: /var/lib/kubelet/pods/
          type: Directory
        name: pods
      - hostPath:
          path: /dev/
          type: ""
        name: dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: umeq-csi-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: umeq-csi-controller
  template:
    metadata:
      labels:
        app: umeq-csi-controller
    spec:
      containers:
      - args:
        - --csi-address=/var/lib/csi/sockets/umeq-csi.xiaomakai.com/csi.sock
        - --leader-election
        - --enable-capacity
        - --capacity-ownerref-level=2
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        image: k8s.gcr.xfs.pub/sig-storage/csi-provisioner:v3.1.0
        imagePullPolicy: IfNotPresent
        name: csi-provisioner
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/csi/sockets/umeq-csi.xiaomakai.com/
          name: socket-dir
      - args:
        - --v=5
        - --csi-address=/var/lib/csi/sockets/umeq-csi.xiaomakai.com/csi.sock
        - --leader-election
        - --http-endpoint=:8080
        env:
        - name: MY_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        image: k8s.gcr.xfs.pub/sig-storage/csi-attacher:v3.4.0
        imagePullPolicy: IfNotPresent
        name: csi-attacher
        ports:
        - containerPort: 8080
          name: http-endpoint
          protocol: TCP
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/csi/sockets/umeq-csi.xiaomakai.com/
          name: socket-dir
      - command:
        - ./plugin
        env:
        - name: CSI_ENDPOINT
          value: /var/lib/csi/sockets/umeq-csi.xiaomakai.com/csi.sock
        - name: AGENT_SERVER
          value: http://192.168.3.11:8080
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        image: kcr.xfs.pub/umeq-csi-plugin:1.0.3
        imagePullPolicy: IfNotPresent
        name: umeq-csi
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/csi/sockets/umeq-csi.xiaomakai.com/
          name: socket-dir
      restartPolicy: Always
      securityContext: {}
      serviceAccount: csi-provisioner
      serviceAccountName: csi-provisioner
      volumes:
      - emptyDir: {}
        name: socket-dir
