kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: my-test-umeq-csi-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard