allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard
provisioner: umeq-csi.xiaomakai.com
parameters:
  kind: default
reclaimPolicy: Delete
volumeBindingMode: Immediate
